---
  - name: Run blog
    docker_container:
      name: blog
      image: alexanderkhomchenkomev/blog:latest
      published_ports:
        - "80:3000"
      exposed_ports:
        - 3000
      state: started
    become: yes

  - name: Run migrations for blog
    shell:
      docker exec -it blog rake db:migrate
    become: yes
