---
- name: Install Postgresql
  apt:
    name: postgresql,postgresql-contrib
    state: present
  become: yes

- name: Create Postgresql database
  postgresql_db:
    name: "{{db_name}}"
  become: yes
  become_user: postgres

- name: Create Postgresql user and grant access to DB
  postgresql_user:
    db: "{{db_name}}"
    name: "{{db_user_name}}"
    password: "{{db_user_password}}"
    priv: "ALL"
    expires: infinity
  become: yes
  become_user: postgres
